measure: fix that retried measurements weren't used
Without the fix if there's an issue encountered in one of the measurements, the half-result is still used, after doing a full remeasurement in the recursion (and dropping those results).

Which may lead to a crash in L349 due to `AttributeError: 'NoneType' object has no attribute 'power'` or to a crash in L353: `ZeroDivisionError: division by zero`